### ISSUE TITLE
Compress strings with escape sequences

### ISSUE THREAD

**Issue by ketan** [siara-cc/Unishox2#10]
Hi,

Thanks for this great library. I'm looking to compress a multiline string (containing whitespace characters`\r` and `\n`). How do I specify the escape sequence in my input file?

Thanks.

**Comment by siara-cc** [comment]
Hi, Thank you for your interest.
You can do it the same way any string is defined in C. Such as:
```C
char *myString = "Hello, This is first line\r\nThis is second line";
```
Or you can read any text file into such strings using standard File I/O (stdio.h) and pass it to this library for compression. The file can have multiple lines or UTF-8 sequences.
