### ISSUE TITLE
Unit Tests and CI for the project

### ISSUE THREAD

**Issue by piponazo** [siara-cc/Unishox2#17]
Hi!

As  you might have noticed I already contributed with 2 PRs and I was thinking if you would be interested in adding unit tests and a 
continuous integration pipeline to the project. I could work in those 2 topics so that it would be easier for people to check if the project is building correctely in certain platforms and have a safety net checking if new changes break the main functionality.

**Comment by siara-cc** [comment]
Hi, as I mentioned elsewhere, I created a CI pipeline for the existing unit tests here: https://github.com/siara-cc/Unishox2/blob/master/.github/workflows/c-cpp.yml
You are most welcome if you would like to improve it. I am closing this issue for now. Thanks!
