### ISSUE TITLE
Unishox for raspberry pi, linux or windows?

### ISSUE THREAD

**Issue by motorhackers** [siara-cc/Unishox2#2]
Is there an unishox version for desktop plataforms?

**Comment by siara-cc** [comment]
This repo is for desktop platforms.  Please see https://github.com/siara-cc/Unishox#compiling for Compiling this on any of the platforms you have mentioned above.
Also please see https://github.com/siara-cc/Unishox#projects-that-use-unishox for projects for other platforms.
