### ISSUE TITLE
[JOSS]: Automated tests

### ISSUE THREAD

**Issue by linuxscout** [siara-cc/Unishox2#32]
- [x] Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified? Not given

**Comment by siara-cc** [comment]
Yes sir, it was probably not mentioned clearly in README.md.  Now I have made a separate section for this:

[Automated tests](https://github.com/siara-cc/Unishox2#unit-tests-automated)

Basically, the `run_unit_tests()` function in `test_unishox2.c` implements over 150 unit tests and there is also a CI pipeline that runs these tests and also test file compression for several files in `sample_text` folder.

**Comment by linuxscout** [comment]
Solved,
 thank you.
