### ISSUE TITLE
Unishox2/Arduino library crashes in append_bits

### ISSUE THREAD

**Issue by mc-hamster** [siara-cc/Unishox2#38]
Hi!

We're looking at implementing this library to be used with the Meshtastic ( https://meshtastic.org ) project but unfortunately there is a runtime error when running the library from just sample code. I've provided a decoded back trace of the execution on an esp32.

Guidance would be appreciated.

Test code in GitHub:

- https://github.com/mc-hamster/Unishox2-Test

This can be opened in Visual Studio Code with PlatformIO using the Arduino Framework.

Thanks mate!

- Jm

Error:

Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d0db9  PS      : 0x00060530  A0      : 0x800d1349  A1      : 0x3ffb1eb0  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000100  A5      : 0x00000001  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x00000080  
A10     : 0x00000001  A11     : 0x00000008  A12     : 0x80000007  A13     : 0xfffffff8  
A14     : 0x3f400198  A15     : 0x00000000  SAR     : 0x0000001f  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x400d0d1e  LEND    : 0x400d0d44  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000

Backtrace: 0x400d0db9:0x3ffb1eb0 0x400d1346:0x3ffb1ed0 0x400d1c4a:0x3ffb1f40 0x400d0cc1:0x3ffb1f70 0x400d2e72:0x3ffb1fb0 0x40086125:0x3ffb1fd0
  #0  0x400d0db9:0x3ffb1eb0 in append_bits(char*, int, unsigned char, int) at src/mesh/compression/unishox2.cpp:707
  #1  0x400d1346:0x3ffb1ed0 in unishox2_compress_lines(char const*, int, char*, unsigned char const*, unsigned char const*, char const**, char const**, us_lnk_lst*) at src/mesh/compression/unishox2.cpp:707
  #2  0x400d1c4a:0x3ffb1f40 in unishox2_compress_simple(char const*, int, char*) at src/mesh/compression/unishox2.cpp:710
  #3  0x400d0cc1:0x3ffb1f70 in setup() at src/main.cpp:24
  #4  0x400d2e72:0x3ffb1fb0 in loopTask(void*) at /Users/jmcasler/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:18
  #5  0x40086125:0x3ffb1fd0 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

Rebooting...

**Comment by siara-cc** [comment]
Hi, it appears to me that no buffer was allocated to hold the decompressed output:
https://github.com/mc-hamster/Unishox2-Test/blob/2a8a3e94e26bee1a378c22ad0d4c2d638dc4b414/src/main.cpp#L23
Also you seem to have adopted the port for Particle Photon.
There were bug fixes and improvements after that so it would be better to use the main source.  Not sure if you were facing any issues including the .c version.

**Comment by mc-hamster** [comment]
Sorry for the slow reply. Been heads down on another project.

The problem with the .c version was I had brought it in from a cpp project and didn't wrap the import in an extern.

I'll create a few code samples and will contribute it back to you. Thanks mate!

Closing this for now.
