### ISSUE TITLE
any golang binding for this?

### ISSUE THREAD

**Issue by hiqsociety** [siara-cc/Unishox2#42]
e.g unishox2.Compress(value)
value := unishox2.Decompress(compressValue)

**Comment by siara-cc** [comment]
I am working on Unishox3, hopefully it will complete soon and I plan to make that available in other popular languages. Meanwhile, you are welcome to attempt it if you have time. I don't have much expertise with Go.  The JS library https://github.com/siara-cc/Unishox_JS may be a good start for this

**Comment by siara-cc** [comment]
See https://github.com/siara-cc/Unishox2/tree/master/other_lang_bindings/go
