### ISSUE TITLE
can u do one just for email? e.g. -.@

### ISSUE THREAD

**Issue by hiqsociety** [siara-cc/Unishox2#43]
can u do one just for email? e.g. -.@

**Comment by siara-cc** [comment]
Not sure if this answers your question, but yes, 
email addresses can be compressed using this library

**Comment by hiqsociety** [comment]
no i mean do 1 just for compressing anything with alphanum, "-", "." , and "@" characters. definitely more efficient right? how do i set what characters to compress only?

**Comment by siara-cc** [comment]
Can use preset 3 as in `./test_unishox2 "arun@siara.cc" 3` but there isn't any difference as @ and . occur only once

**Comment by hiqsociety** [comment]
i think the compression can be better with only 3 symbols and not all?
 
right?

is there a way to set the symbols for compression? this will be even better.

**Comment by siara-cc** [comment]
If you see the model at https://github.com/siara-cc/Unishox2/blob/master/promo/model.png?raw=true
most symbols you have mentioned are at favorable positions except perhaps @ and -.
Even if we do as you mentioned, we may get 1 byte improvement at the max as these symbols mostly appear only once.
You could try it out by changing the symbol table in the code by moving all symbols to beginning of Set 2 and also use 2 as preset.

**Comment by hiqsociety** [comment]
1 byte improvement is very very very good for email addresses.

i think next version shld hv a way for user to define the symbols easier as i've mentioned.

to change hard coded values, i'm kind of worried will hv breaking changes.
will u do the user defined symbols add on?

**Comment by hiqsociety** [comment]
i just realised user defined symbols table can and will compress even better!
u shld do that as unishox3 or something

**Comment by siara-cc** [comment]
Sure I will provide a way for developer or user to customise the symbol table in next version. Thanks!

**Comment by siara-cc** [comment]
I created a separate branch favor-email and changed the symbol table to favour "@,_,.,-". Also created a preset for email with frequency list as "@gmail.com, "@yahoo.com", "@hotmail.com", ".com", ".net" and ".org" and the savings were found to be more than just 1 byte.  If you would like to try it:

```
git clone -b favor-email https://github.com/siara-cc/Unishox2 Unishox2_email
cd Unishox2_email
make
./test_unishox2 "arun@gmail.com" 17
```
