### ISSUE TITLE
great work by the way, what's the difference between w-olen and without?

### ISSUE THREAD

**Issue by hiqsociety** [siara-cc/Unishox2#44]
-rwxr-xr-x  1 root root  86208 Jun 23 13:27 test_unishox2
-rwxr-xr-x  1 root root  86208 Jun 23 13:27 test_unishox2-w-olen

**Comment by hiqsociety** [comment]
i didnt really see the diff in output but will close this anyway. thx

**Comment by siara-cc** [comment]
No difference expected in output or execution.  The -w-olen compiles with UNISHOX_API_WITH_OUTPUT_LEN, which allows developer to specify output buffer size for compress and decompress to make sure that the library does not write beyond given buffer size.

It is only for developers who compile the library with their own code.
