### ISSUE TITLE
when is unishox 3 ready? just curious. been watching this repo for a year+

### ISSUE THREAD

**Issue by hiqsociety** [siara-cc/Unishox2#57]
when is unishox 3 ready? just curious. been watching this repo for a year+
is there an ETA for unishox 3?

**Comment by siara-cc** [comment]
Hi, sorry to keep you waiting. I am still working on it trying to arrive at a perfect static dictionary with [this project](https://github.com/siara-cc/Text_frequency_research) and [this project](https://github.com/siara-cc/rankstacked-trie).
As of now we have Unishox3 Alpha, which I will not be changing so if you use it to compress a string, it will always be possible to decompress it back without worry about compatibility issues.
The compression ratio is not expected to be too much different with the actual release.
I don't have any particular ETA but hoping to wrap it up by end of the year.

**Comment by siara-cc** [comment]
I think golang binding should not be too difficult as I already made one for Unishox2 here: https://github.com/siara-cc/Unishox2/tree/master/other_lang_bindings/go
I will try to get it done by next week

**Comment by siara-cc** [comment]
@hiqsociety  I have committed the binding for golang here: https://github.com/siara-cc/Unishox2/tree/master/other_lang_bindings/go

However when testing it, I found it works for normal strings, but gives a seg fault for strings containing smileys.  I will check when I get more time.

**Comment by sergeevabc** [comment]
Dear fellows, could you be so kind to compile Unishox for mere Windows x64 users without compilers? Even .zip attached here would be appreciated.

**Comment by hiqsociety** [comment]
@siara-cc thx for the golang binding! looking forward to unishox 3 release.

do provide a section where i can buy u a coffee or for others to sponsor this great project!
