### ISSUE TITLE
Arduino compatible version with max output length in API?

### ISSUE THREAD

**Issue by thebentern** [siara-cc/Unishox2#59]
In the Meshtastic project we had previously been using the unishox2.c implementation of `unishox2_compress_simple` but ran into some issues with high entropy strings blowing out the size of the output buffer in some cases and causing runtime faults. So naturally we looked to the documentation which suggested moving toward the non-simple method examples which allow an output size with setting the `UNISHOX_API_WITH_OUTPUT_LEN` macro. 

This approach however led to the discovery that while unishox2.c compiles just fine in GCC, in the Arduino environment the preset macros break during compilation, for example:
`src/mesh/compression/unishox2.h:205:5: error: taking address of temporary array
     {                                                                                                    
                        \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "\": \"", "\": ", "</", "=\"", "\":\"", "://"                                                    
                        \
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     }
     ~
src/mesh/compression/unishox2.h:248:61: note: in expansion of macro 'USX_FREQ_SEQ_DFLT'
 #define USX_PSET_DFLT USX_HCODES_DFLT, USX_HCODE_LENS_DFLT, USX_FREQ_SEQ_DFLT, USX_TEMPLATES
                                                             ^~~~~~~~~~~~~~~~~
note: in expansion of macro 'USX_PSET_DFLT'
in...
             auto length = unishox2_compress_lines(input, strlen(input), output, sizeof(output), USX_PSET_DFLT, NULL);`

Our second approach was to take another look at the Arduino implementation you have added, but unfortunately, we noted that there was no maximum output length restriction as in the unishox2.c implementation. Do you have any strategies to help us work around this issue?

Thanks again for a fantastic compression library! 😄

**Comment by siara-cc** [comment]
@thebentern I will update the Arduino implementation with the latest changes to the C version.  Are there any issues with the present Arduino version on your board?

**Comment by siara-cc** [comment]
@thebentern I updated the Arduino as well as the main unishox2.* implementations.  I also added a sample sketch to demonstrate passing of output length for compression and decompression.  It works on esp32.
The initial Arduino port for Particle Photon was contributed by Jonathan Greenblat.

**Comment by thebentern** [comment]
> @thebentern I updated the Arduino as well as the main unishox2.* implementations. I also added a sample sketch to demonstrate passing of output length for compression and decompression. It works on esp32. The initial Arduino port for Particle Photon was contributed by [Jonathan Greenblat](https://github.com/leafgarden) and checks for output length was contributed by [James Z.M. Gao](https://github.com/gsm55) over several PRs.

Wow! That was a fast response. Thanks so much! 
I'll give it a whirl and see how it goes. 😄

**Comment by siara-cc** [comment]
@thebentern As I understand how this works for meshtastic, you have a limit of around 100+ bytes for the input message and I assume a buffer of same size would have been allocated for the compressed bytes.

I am wondering what kind of high entropy strings users enter that makes the compressed bytes more than the input size? Any kind of text that is used in conversation of such size will definitely give some little compression at least?

**Comment by thebentern** [comment]
> I am wondering what kind of high entropy strings users enter that makes the compressed bytes more than the input size? Any kind of text that is used in conversation of such size will definitely give some little compression at least?

These were deliberately engineered high entropy strings.
https://github.com/meshtastic/firmware/issues/3841
