### ISSUE TITLE
Inefficiency Compressing Chinese.

### ISSUE THREAD

**Issue by SheepChef** [siara-cc/Unishox2#60]
I've recently tested the same Chinese sentence on README using Unishox2 1.0.3

```
Result:

神>馊 堻梱X鷽X6y'僞G洌美是心?B?&
美是不是在脸上。美是心中的亮光。
CompressedUint8Vec(Bytes): 46
OriginalUint8Vec(Bytes): 32
```

It seemed that Compressed data size is bigger than Original.

You may wondering how did I test it, here is the code.

```C++
#include <iostream>
#include <string.h>
#include <bitset>
#include <vector>
#include <unishox2.h>
#include <unishox2.c> 

using namespace std;

std::vector<uint8_t> String2Uint8T(const std::string& str) { //把字符串拆解成字节数组
    std::vector<uint8_t> result(str.begin(), str.end());
    return result;
}
int main(){
	string str =u8"美是不是在脸上。美是心中的亮光。";
	string test;
	const char* str2 = str.c_str();
	char* test2 = new char[str.length()]; //Store the Comressed Data
	char* test3 = new char[str.length()]; // Store the Decompressed Data
	
	int Comlength = unishox2_compress_simple(str2 ,str.length(), test2);
	
	cout<<test2<<endl;             //神>馊 堻梱X鷽X6y'僞G洌美是心?B?&
	vector<uint8_t> data = String2Uint8T(test2); //So data is the Compressed data stored in bytes.
	vector<uint8_t> data2 = String2Uint8T(str); // data2 is the original str stored in bytes.
	
	
	int Comlength2 = unishox2_decompress_simple(test2, Comlength, test3);
	for(int i=0;i<Comlength2;i++){
		cout<<test3[i];              //美是不是在脸上。美是心中的亮光。
	} 
	cout<<endl;
	
	cout<<"CompressedUint8Vec(Bytes): "<<" "<<Comlength<<endl<<"OriginalUint8Vec(Bytes): "<<data2.size();
	delete[] test2;
	delete[] test3;
}
```

So obviously there is something wrong here.

I don't know if there is anything I could do.

**Comment by SheepChef** [comment]
![image](https://github.com/user-attachments/assets/2e78b61d-66bd-430b-a7a6-81e9e34f2772)
In contrast, here is a random magnet link i found on web.

**Comment by siara-cc** [comment]
@SheepChef  I tried your input with the command line utility given with Unishox and it does compress Chinese, although there is not much savings compared to other languages:

![image](https://github.com/user-attachments/assets/47ffcde0-fa1d-4b29-8425-8f5d19720a00)

The problem could be because the present implementation only supports UTF-8. You would need to pass UTF-8 char array to `unishox_compres_simple`.

**Comment by SheepChef** [comment]
UTF-8 Char array?

I mean, I specified the string to be u8, and it seemed to be UTF-8 according to its size.

And as you see, I used c_str() to transform it into a char array.

**Comment by SheepChef** [comment]
Oh, I noticed that the string size is actually 2x the number of letters.

Normally it should be 3x , so it is not UTF-8 but an ASCII derivative called GBK2312.....

**Comment by SheepChef** [comment]
Okay the problem is that my source file is saved in ANSII

**Comment by SheepChef** [comment]
![image](https://github.com/user-attachments/assets/0ba79a4c-2888-41b6-a84d-df1c324e74c4)

Alright, seemed legitimate.

I really hate how C++ handles multi-byte UTF-8 characters.

**Comment by siara-cc** [comment]
@SheepChef UTF-8 is not the same as u8 or uint8. Please read about UTF-8 here: https://en.wikipedia.org/wiki/UTF-8

**Comment by SheepChef** [comment]
> @SheepChef UTF-8 is not the same as u8 or uint8. Please read about UTF-8 here: https://en.wikipedia.org/wiki/UTF-8

Thanks for reviewing my dumb question...

I didn't even notice that my cpp file is saved in ANSI

**Comment by siara-cc** [comment]
No problem. I think UTF-8 is not much used for Chinese or languages of same kind.

**Comment by SheepChef** [comment]
> No problem. I think UTF-8 is not much used for Chinese or languages of same kind.

Sorry for disturbing, but may I ask if there is any method to tell if give data is compressed?

I know there are magic bits, but it seemed only being editable in C++, while I need to keep my project consistent on these two platforms.

**Comment by SheepChef** [comment]
https://github.com/siara-cc/unishox_js/blob/87d4c2b3a5363b24797c7399d4c1afaa060ae808/unishox2.js#L475C2-L475C57

As I checked the JS magic bits is hard-coded as 0x80 and lengthed 1 bit
